name: Integration testing
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install libgconf
        run: sudo apt-get update && sudo apt-get install -yq libgconf-2-4
      - name: Install NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: Check out code
        uses: actions/checkout@master
      - name: Use cache
        uses: actions/cache@preview
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Build
        run: yarn install --frozen-lockfile && yarn run initialize && yarn run compile
      - name: Lint
        run: yarn run lint
      - name: Test
        env:
          CI: true
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          FOSSA_API_KEY: ${{ secrets.FOSSA_API_KEY }}
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
        run: yarn start-server-and-test ci:start "3000|2996/status" "yarn lerna run cypress:run:ci --scope re-radio-e2e"
